---
- name: Install and configure jboss-as on centOS 
  hosts: centos #groupe d'hotes du fichier hosts
  remote_user: ansible #utilisateur distant
  become: yes #authorisation a devenir admin
  become_method: sudo #en utilisant sudo
  gather_facts: no #ne pas récuperer les infos des machines (gain de temps)

  vars_prompt: # récupérations de quelques variables saisies par l'utilisateur
    - name: "location"
      prompt: "Dans quel répertoire souhaitez-vous installer Jboss AS ? un dossier sera ensuite cree"
      private: no

    - name: "dir_name"
      prompt: "Comment souhaitez-vous nommer le dossier JBOSS ? (par défaut: jboss-as)"
      private: no
      default: jboss-as
 
    - name: "java_home"
      prompt: "Dans quel repertoire souhaitez-vous installer java jdk 1.7 ?"
      private: no

    - name: "xmx"
      prompt: "Quelle quantité de mémoire souhaitez vous allouer a la jvm ?"
      private: no
      
    - name: "http_port"
      prompt: "Indiquez le port d écoute http pour cette installation (defaut: 8080)"
      private: no
      default: 8080

    - name: "https_port"
      prompt: "Indiquez le port d écoute https pour cette installation (defaut: 8443)"
      private: no
      default: 8443

    - name: "management_port"
      prompt: "Indiquez le port de l'interface de management http pour cette installation (defaut: 9990)"
      private: no
      default: 9990

    - name: "native_mgm_port"
      prompt: "Indiquez le port de management natif (defaut: 9999)"
      private: no
      default: 9999
 
    - name: "remote_port"
      prompt: "Indiquez le port de remoting (defaut: 4447)"
      private: no
      default: 4447

    - name: "jboss_user"
      prompt: "Indiquez le nom de l'utilisateur jboss (chargé d'executer jboss, par defaut: jboss) ?"
      private: no
      default: jboss

    - name: "jboss_mgmt_user"
      prompt: "Indiquez le nom de l'utilisateur dédié a la console de management web (par defaut: admin)"
      private: no
      default: admin

    - name: "jboss_passwd"
      prompt: "Jboss user password ?"
      private: yes

    - name: "address" 
      prompt: "Indiquez l'adresse écoutée par le controleur local (si besoin, par defaut: 127.0.0.1)"
      private: no
      default: 127.0.0.1

    - name: "start_delay"
      prompt: "Précisez le delai en secondes pour le démarrage de boss (par defaut: 1)"
      private: no
      default: 1

    - name: "stop_delay"
      prompt: "Précisez le delai en secondes pour l'extinction de jboss (par defaut: 1)"
      private: no
      default: 1

  tasks:
    - name: Envoi jboss-as
      unarchive: #module zip/tar/gz
        src: /etc/ansible/roles/files/jboss-as-7.1.3.Final.zip #source du fichier présent sur la machine hote (le modulel unarchive envoi et dézip dans la foulée)
        dest: "{{ location }}" #variable location

    #équivalent d'un mkdir avec l'argument state
    - name: create directory Java (/usr/java)
      file: 
        path: "{{ java_home }}/java"
        state: directory
        mode: 0755

    - name: unarchive jdk
      unarchive:
        src: /etc/ansible/roles/files/jdk-7u80-linux-x64.tar.gz
        dest: "{{ java_home }}/java"

    #verifie que l'archive a bien étée envoyée dézipée au bon endroit
    - name: check jboss as directory name
      stat: 
        path: "{{ location }}/jboss-as-7.1.3.Final"
      register: ln #enregistre la réponse

    #verifie que le dossier 'dir_name' n'éxiste pas déja
    - name: check jboss as directory exist
      stat: 
        path: "{{ location }}/{{ dir_name }}"
      register: sn

    - name: rename directory jboss-as
      shell: 'mv "{{ location }}/jboss-as-7.1.3.Final" "{{ location }}/{{ dir_name }}"' #commande bash pour renommer le dossier
      when: ln.stat.exists == True and sn.stat.exists == False #seulement si ls.stat existe et sn.stat n'existe pas (les deux stats du dessus)
      
    #crée un groupe sur les machines distantes
    - name:  create group jboss on Centos
      group: 
        name: jboss

    #crée un user et lui ajoute un group et un home précis
    - name: create user jboss on Centos
      user: 
        name: jboss
        group: jboss
        home: "{{ location }}/{{ dir_name }}"

    #ajout d'un bloc de plusieurs lignes dans le fichier de dest spécifié
    - name: give JAVA_HOME to jboss build script
      blockinfile:
        dest: "{{ location }}/{{ dir_name }}/build.sh"
        insertafter: "#!/bin/sh" 
        content: "JAVA_HOME={{ java_home }}/java/jdk1.7.0_80 \n
          export JAVA_HOME \n 
          PATH=$PATH:$JAVA_HOME \n
          export PATH \n"

    #ajout une ligne dans un fichier spécifié
    - name: increase memory limit for build (1280Mo required)
      lineinfile: 
        path="{{ location }}/{{ dir_name }}/build.sh"
        regexp='^MAVEN_OPTS='
        line='MAVEN_OPTS="$MAVEN_OPTS -Xms1280M -Xmx1280M"'

    - name: build it (may take a long time, about 30 min)
      shell: '"{{ location }}/{{ dir_name }}/build.sh" -Dmaven.test.skip=true' #commande bash pour executer l'installeur
    
    #équivalent d'un chown -R
    - name: change ownership of jboss-as
      file: 
        path: "{{ location }}/{{ dir_name }}"
        owner: jboss
        group: jboss
        state: directory
        recurse: yes

    - name: give JAVA_HOME to the standalone script
      blockinfile:
        dest: "{{ location }}/{{ dir_name }}/build/target/jboss-as-7.1.3.Final/bin/standalone.sh"
        insertafter: "#!/bin/sh"
        content: "JAVA_HOME={{ java_home }}/java/jdk1.7.0_80 \n
          export JAVA_HOME \n
          PATH=$PATH:$JAVA_HOME \n
          export PATH \n"
          
    #ici on va changer les ports spécifiées au début du playbook par l'utilisateur
    - name: set http port
      lineinfile:
        path="{{ location }}/{{ dir_name }}/build/target/jboss-as-7.1.3.Final/standalone/configuration/standalone.xml"
        regexp='<socket-binding name="http" '
        line='        <socket-binding name="http" port="{{ http_port }}"/>'

    - name: set https port
      lineinfile:
        path="{{ location }}/{{ dir_name }}/build/target/jboss-as-7.1.3.Final/standalone/configuration/standalone.xml"
        regexp='<socket-binding name="https" '    
        line='        <socket-binding name="https" port="{{ https_port }}"/>'

    - name: set http management port
      lineinfile:
        path="{{ location }}/{{ dir_name }}/build/target/jboss-as-7.1.3.Final/standalone/configuration/standalone.xml"
        regexp='<socket-binding name="management-http" interface="management" '
        line='        <socket-binding name="management-http" interface="management" port="${jboss.management.http.port:{{ management_port }}}"/>'

    - name: set address
      replace:
        dest="{{ location }}/{{ dir_name }}/build/target/jboss-as-7.1.3.Final/standalone/configuration/standalone.xml"
        regexp="127.0.0.1"
        replace="{{ address }}"

    - name: set remoting port
      lineinfile:
        path="{{ location }}/{{ dir_name }}/build/target/jboss-as-7.1.3.Final/standalone/configuration/standalone.xml"
        regexp='<socket-binding name="remoting" '
        line='        <socket-binding name="remoting" port="{{ remote_port }}"/>'

    - name: set native port
      lineinfile:
        path="{{ location }}/{{ dir_name }}/build/target/jboss-as-7.1.3.Final/standalone/configuration/standalone.xml"
        regexp='<socket-binding name="management-native" interface="management" '
        line='        <socket-binding name="management-native" interface="management" port="${jboss.management.native.port:{{ native_mgm_port }}}"/>'

    #copie d'un fichier déja présent sur la machine distante et chmod 0755
    - name: copy init.d file
      copy: 
        src: "{{ location }}/{{ dir_name }}/build/target/jboss-as-7.1.3.Final/bin/init.d/jboss-as-standalone.sh"
        dest: /etc/init.d/jboss
        remote_src: true
        mode: 0755

    #modifications de 4 lignes differentes dans un meme fichier
    - name: setup env
      lineinfile: 
        path: /etc/init.d/jboss
        regexp: "{{ item.line_to_match }}"
        line: "{{ item.line_to_configure }}"
      with_items:
        - { line_to_match: "JBOSS_HOME=", line_to_configure: "JBOSS_HOME={{ location }}/{{ dir_name }}/build/target/jboss-as-7.1.3.Final/" }
        - { line_to_match: "JBOSS_CONSOLE_LOG=", line_to_configure: "JBOSS_CONSOLE_LOG={{ location }}/{{ dir_name }}/console.log" }
        - { line_to_match: "STARTUP_WAIT=", line_to_configure: "STARTUP_WAIT={{ start_delay }}" }
        - { line_to_match: "STARTUP_STOP=", line_to_configure: "STARTUP_STOP={{ stop_delay }}" }
        
       # - { line_to_match: "", line_to_configure: " " } 
    
    - name: add jboss user name
      lineinfile: 
        dest: /etc/init.d/jboss   
        insertbefore: 'JBOSS_SCRIPT='
        line: 'JBOSS_USER=jboss'

    #module service qui enable et start le service jboss
    - name: enable and start jboss-as service
      service:
        name: jboss
        state: started
        enabled: yes

     #inclusion du playbook qui gère l'ajout d'un utilisateur a la console de management
    - include: jboss_mng_usr.yml 
