---
- name: Install and configure jboss-as on centOS
  hosts: centos
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: no

  vars_prompt:
    - name: "location"
      prompt: "Indiquez l'emplacement du répertoire parent de Jboss AS ?"
      private: no
      
    - name: "jboss_user"
      prompt: "Jboss user ?"
      private: no
    
    - name: "jboss_passwd"
      prompt: "Jboss user password ?"
      private: yes

  tasks:
    - name: create java encryption file
      blockinfile:
        dest: "{{ location }}/jboss-as/EncryptPassword.java"
        create: yes
        mode: 0755
        marker: "/* {mark} ANSIBLE MANAGED BLOCK */"
        block: |
          import java.security.MessageDigest;
          import java.math.BigInteger;
          import org.jboss.crypto.CryptoUtil;

          public class EncryptPassword
            {
              public static void main(String ar[]) throws Exception
               {
                 String userName=ar[0];
                 String realmName=ar[1];
                 String password=ar[2];

                 String clearTextPassword=userName+":"+realmName+":"+password;

                 String hashedPassword=CryptoUtil.createPasswordHash("MD5", "hex", null, null, clearTextPassword);
                 System.out.println(hashedPassword);
               }
            }

    - name: javac EncryptPassword
      shell: 'echo $CLASSPATH; /usr/java/jdk1.7.0_80/bin/javac EncryptPassword.java'
      args:
        chdir: "{{ location }}/jboss-as/"
      environment:
        JBOSS_HOME: '{{ location }}/jboss-as/build/target/jboss-as-7.1.3.Final/'
        CLASSPATH: '{{ location }}/jboss-as/build/target/jboss-as-7.1.3.Final/modules/org/picketbox/main/picketbox-4.0.13.Final.jar:{{ location }}/jboss-as/build/target/jboss-as-7.1.3.Final/bin/client/jboss-client.jar:$CLASSPATH:.:'
    - name: add jboss user name
      shell: 'java EncryptPassword {{ jboss_user }} ManagementRealm  {{ jboss_passwd }}'
      args:
        chdir: "{{ location }}/jboss-as/"
      environment:
        JBOSS_HOME: '{{ location }}/jboss-as/build/target/jboss-as-7.1.3.Final/'
        CLASSPATH: '{{ location }}/jboss-as/build/target/jboss-as-7.1.3.Final/modules/org/picketbox/main/picketbox-4.0.13.Final.jar:{{ location }}/jboss-as/build/target/jboss-as-7.1.3.Final/bin/client/jboss-client.jar:$CLASSPATH:.:'
      register: hashed
    
    - set_fact:
        hashed_passwd: "{{ hashed.stdout }}"

    - name: store passwd in right file
      lineinfile:
        dest: '{{ location }}/jboss-as/build/target/jboss-as-7.1.3.Final/standalone/configuration/mgmt-users.properties'
        state: present
        line: '{{ jboss_user  }}={{ hashed_passwd }}'
