---
- name: install apache2
  hosts: grp2test
  remote_user: ansible
  become: yes
  become_method: su
  become_user: root
  tasks:
    - name: ensure servers are up to date
      apt:
        update_cache: yes
        upgrade: full

    - name: install apache2
      apt: 
        name=apache2 
        update_cache=yes 
        state=latest

    - name: enable mod_rewrite
      apache2_module: 
        name=rewrite 
        state=present
      notify:
        - restart apache2
    
 
  handlers:
    - name: restart apache2
      service: 
        name=apache2 
        state=restarted
