---
#activation de windows IIS et mise en place d'une page web
- name: Install IIS web server and a Web Site
  hosts: windows
  remote_user: ansible
  tasks:
    #module win_feature permet de gerer les outils présents dans windows server
    - name: install IIS and management tools
      win_feature:
        name: Web-Server
        state: present
        include_management_tools: True
        restart: no 
        
    #module win_iis_website permet ensuie de gerer les sites de l'outil    
    - name: remove Default Web Site
      win_iis_website:
        name: Default Web Site
        state: absent
    
    #création d'un dossier
    - name: create directory hola
      win_file:
        path: C:\inetpub\hola
        state: directory
        
     #copie de l'index.html   
    - name: send index.html file
      win_copy:
        src: /etc/ansible/roles/common/files/index.html
        dest: C:\inetpub\hola\ 
        
    - name: create directory logs
      win_file:
        path: C:\inetpub\hola\logs
        state: directory
    
    #setup du site web via module iis_website
    - name: setup web site hola
      win_iis_website:
        name: Hola
        state: started
        port: 8080
        physical_path: C:\inetpub\hola
        parameters: logfile.directory:C:\inetpub\hola\logs
