---
- name: install apache2
  hosts: toto
  remote_user: root
  become: yes
  become_method: su
  tasks:
    - name: ensure servers are up to date
      apt:
        update_cache: yes
        upgrade: full

    - name: install apache2
      apt: 
        name=apache2 
        update_cache=yes 
        state=latest

    - name: enable mod_rewrite
      apache2_module: 
        name=rewrite 
        state=present
      notify:
        - restart apache2
    
    - name: change index.html file
      template:
        src: /etc/ansible/files/index.html
        dest: /var/www/html/index.html
 
  handlers:
    - name: restart apache2
      service: 
        name=apache2 
        state=restarted
